app:
  csv-folder: /Users/shiraishitoshio/bookmaker/csv/
  output-csv-folder: /Users/shiraishitoshio/bookmaker/outputs/
  team-csv-folder: /Users/shiraishitoshio/bookmaker/teams_by_league/
  future-csv-folder: /Users/shiraishitoshio/bookmaker/future/
  b001-json-folder: /Users/shiraishitoshio/bookmaker/json/b001/
  b008-json-folder: /Users/shiraishitoshio/bookmaker/json/b008/

process:
  python:
    root: ${PY_ROOT:/opt/team_master_python}
    pythonBin: ${PY_BIN:python3}
  s3:
    region: ${AWS_REGION:ap-northeast-1}
    buckets:
      teamSeasonDateData: ${S3_TEAM_SEASON_DATE_DATA:aws-s3-season-csv}
      teamData: ${S3_TEAM_DATA:aws-s3-team-csv}
      teamMemberData: ${S3_TEAM_MEMBER_DATA:aws-s3-team-member-csv}
      outputs: ${S3_OUTPUTS:aws-s3-outputs-csv}
      future: ${S3_FUTURE:aws-s3-future-csv}
      stats: ${S3_STATS:aws-s3-stat-csv}
      allLeague: ${S3_ALL_LEAGUE:aws-s3-all-league-csv}

spring:
  datasource:
    bm:
      jdbc-url: jdbc:postgresql://localhost:54320/soccer_bm
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver
    master:
      jdbc-url: jdbc:postgresql://localhost:54320/soccer_bm_master
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:54320/soccer_bm_master
    user: postgres
    password: sonic3717
    driver-class-name: org.postgresql.Driver

mybatis:
  type-handlers-package: dev.application.mybatis
  configuration:
    auto-mapping-unknown-column-behavior: WARNING
    map-underscore-to-camel-case: true
