openapi: 3.0.0
info:
  title: Make Eval API
  description: 評価管理に関するAPI
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /eval/get/{evalid}:
    get:
      summary: 評価管理情報の取得
      parameters:
        - in: path
          name: evalid
          required: true
          description: 評価管理ーID
          schema:
            type: string
            example: "E00001"
      responses:
        '200':
          description: 評価管理情報取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: リクエストが不正です
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUpdateDeleteGetRequestResponse'
        '404':
          description: 対応する評価管理IDが存在しません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGetResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorServerInnerResponse'
  /books/create/{evalid}:
    post:
      summary: 評価管理作成
      parameters:
        - in: path
          name: evalid
          required: true
          description: 評価管理ID
          schema:
            type: string
            example: "E00001"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '200':
          description: 評価管理情報作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: リクエストが不正です
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCreateRequestResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorServerInnerResponse'
  /books/update/{evalid}:
    patch:
      summary: 評価管理情報の更新
      parameters:
        - in: path
          name: evalid
          required: true
          description: 評価管理ーID
          schema:
            type: string
            example: "E00001"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '200':
          description: 評価管理情報更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: リクエストが不正です
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUpdateDeleteGetRequestResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorServerInnerResponse'
  /books/delete/{evalid}:
    delete:
      summary: 評価管理情報の削除
      parameters:
        - in: path
          name: evalid
          required: true
          description: 評価管理ID
          schema:
            type: string
            example: "E00001"
      responses:
        '200':
          description: 評価管理情報削除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: リクエストが不正です
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUpdateDeleteGetRequestResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorServerInnerResponse'
components:
  schemas:
    Review:
      type: object
      required:
        - evalid
        - reviewid
      properties:
        evalid:
          type: string
          example: "E00001"
        reviewid:
          type: string
          example: "R00001"
          
    SuccessResponse:
      type: object
      properties:
        code:
          type: string
          example: 200
        message:
          type: string
          example: 処理成功
          
    ErrorCreateRequestResponse:
      type: object
      properties:
        code:
          type: string
          example: 400
        message:
          type: string
          example: 入力値が不正です
        details:
          type: string
          example: evalidは必須です
          
    ErrorUpdateDeleteGetRequestResponse:
      type: object
      properties:
        code:
          type: string
          example: 400
        message:
          type: string
          example: evalidが不正です
          
    ErrorGetResponse:
      type: object
      properties:
        code:
          type: string
          example: 404
        message:
          type: string
          example: 存在しないevalidです
          
    ErrorServerInnerResponse:
      type: object
      properties:
        code:
          type: string
          example: 500
        message:
          type: string
          example: サーバー内エラーです
