INSERT INTO data (
    seq,
    condition_result_data_seq_id,
    data_category,
    times,
    home_rank,
    home_team_name,
    home_score,
    away_rank,
    away_team_name,
    away_score,
    home_exp,
    away_exp,
    home_in_goal_exp,
    away_in_goal_exp,
    home_donation,
    away_donation,
    home_shoot_all,
    away_shoot_all,
    home_shoot_in,
    away_shoot_in,
    home_shoot_out,
    away_shoot_out,
    home_block_shoot,
    away_block_shoot,
    home_big_chance,
    away_big_chance,
    home_corner,
    away_corner,
    home_box_shoot_in,
    away_box_shoot_in,
    home_box_shoot_out,
    away_box_shoot_out,
    home_goal_post,
    away_goal_post,
    home_goal_head,
    away_goal_head,
    home_keeper_save,
    away_keeper_save,
    home_free_kick,
    away_free_kick,
    home_offside,
    away_offside,
    home_foul,
    away_foul,
    home_yellow_card,
    away_yellow_card,
    home_red_card,
    away_red_card,
    home_slow_in,
    away_slow_in,
    home_box_touch,
    away_box_touch,
    home_pass_count,
    away_pass_count,
    home_long_pass_count,
    away_long_pass_count,
    home_final_third_pass_count,
    away_final_third_pass_count,
    home_cross_count,
    away_cross_count,
    home_tackle_count,
    away_tackle_count,
    home_clear_count,
    away_clear_count,
    home_duel_count,
    away_duel_count,
    home_intercept_count,
    away_intercept_count,
    record_time,
    weather,
    temparature,
    humid,
    judge_member,
    home_manager,
    away_manager,
    home_formation,
    away_formation,
    studium,
    capacity,
    audience,
    location,
    home_max_getting_scorer,
    away_max_getting_scorer,
    home_max_getting_scorer_game_situation,
    away_max_getting_scorer_game_situation,
    home_team_home_score,
    home_team_home_lost,
    away_team_home_score,
    away_team_home_lost,
    home_team_away_score,
    home_team_away_lost,
    away_team_away_score,
    away_team_away_lost,
    notice_flg,
    game_link,
    goal_time,
    goal_team_member,
    judge,
    home_team_style,
    away_team_style,
    probablity,
    prediction_score_time,
    game_id,
    match_id,
    time_sort_seconds,
    add_manual_flg,
    logic_flg,
    register_id,
    register_time,
    update_id,
    update_time
) VALUES
    ('138845', '1', '日本: J2 リーグ - ラウンド 18', '10:27', '16.', 'ブラウブリッツ秋田', '0', '17.', 'カターレ富山', '0', NULL, NULL, NULL, NULL, '60%', '40%', NULL, NULL, '0', '0', '1', '0', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:14:12+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '---', '---', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138846', '1', '日本: J2 リーグ - ラウンド 18', '13:56', '16.', 'ブラウブリッツ秋田', '0', '17.', 'カターレ富山', '0', NULL, NULL, NULL, NULL, '47%', '53%', NULL, NULL, '0', '0', '1', '0', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', '3', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:17:40+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '---', '---', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138847', '1', '日本: J2 リーグ - ラウンド 18', '17:16', '16.', 'ブラウブリッツ秋田', '0', '17.', 'カターレ富山', '0', NULL, NULL, NULL, NULL, '50%', '50%', NULL, NULL, '0', '0', '1', '0', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', '3', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:21:00+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '---', '---', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138848', '1', '日本: J2 リーグ - ラウンド 18', '20:47', '16.', 'ブラウブリッツ秋田', '0', '17.', 'カターレ富山', '0', NULL, NULL, NULL, NULL, '49%', '51%', NULL, NULL, '0', '3', '1', '0', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '3', '1', '0', '3', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:24:35+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '---', '---', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138849', '1', '日本: J2 リーグ - ラウンド 18', '23:53', '18.', 'ブラウブリッツ秋田', '0', '13.', 'カターレ富山', '1', NULL, NULL, NULL, NULL, '42%', '58%', NULL, NULL, '0', '4', '1', '0', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '3', '1', '1', '3', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:27:44+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '23''', '碓井 聖生', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138850', '1', '日本: J2 リーグ - ラウンド 18', '32:03', '18.', 'ブラウブリッツ秋田', '0', '13.', 'カターレ富山', '1', NULL, NULL, NULL, NULL, '39%', '61%', NULL, NULL, '0', '4', '2', '2', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', '5', '1', '1', '4', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:35:47+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '23''', '碓井 聖生', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138851', '1', '日本: J2 リーグ - ラウンド 18', '34:30', '18.', 'ブラウブリッツ秋田', '0', '13.', 'カターレ富山', '1', NULL, NULL, NULL, NULL, '39%', '61%', NULL, NULL, '0', '4', '3', '2', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', '5', '1', '1', '4', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:38:15+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '23''', '碓井 聖生', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138852', '1', '日本: J2 リーグ - ラウンド 18', '47:55', '18.', 'ブラウブリッツ秋田', '0', '13.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '42%', '58%', NULL, NULL, '0', '5', '3', '3', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', '10', '1', '1', '7', '2', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:51:43+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '42''', '植田 啓太', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138853', '1', '日本: J2 リーグ - ラウンド 18', 'ハーフタイム', '18.', 'ブラウブリッツ秋田', '0', '13.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '42%', '58%', NULL, NULL, '0', '5', '3', '4', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '10', '1', '1', '10', '4', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:07:53+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '42''', '植田 啓太', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138854', '1', '日本: J2 リーグ - ラウンド 18', '50:15', '18.', 'ブラウブリッツ秋田', '0', '13.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '42%', '58%', NULL, NULL, '0', '5', '3', '3', NULL, NULL, NULL, NULL, '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '10', '1', '1', '7', '4', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 14:54:01+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '未出場', '未出場', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '42''', '植田 啓太', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138855', '1', '日本: J2 リーグ - ラウンド 18', '51:06', '18.', 'ブラウブリッツ秋田', '1', '13.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '39%', '61%', NULL, NULL, '1', '5', '4', '4', NULL, NULL, NULL, NULL, '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '10', '1', '1', '10', '4', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:14:47+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '46''', '小松 蓮', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138856', '1', '日本: J2 リーグ - ラウンド 18', '54:39', '18.', 'ブラウブリッツ秋田', '1', '13.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '40%', '60%', NULL, NULL, '1', '5', '4', '5', NULL, NULL, NULL, NULL, '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '10', '1', '1', '10', '4', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:18:24+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '46''', '小松 蓮', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138857', '1', '日本: J2 リーグ - ラウンド 18', '59:11', '18.', 'ブラウブリッツ秋田', '1', '13.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '40%', '60%', NULL, NULL, '1', '5', '4', '5', NULL, NULL, NULL, NULL, '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '12', '1', '1', '10', '4', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:22:53+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '46''', '小松 蓮', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138858', '1', '日本: J2 リーグ - ラウンド 18', '60:18', '18.', 'ブラウブリッツ秋田', '1', '13.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '40%', '60%', NULL, NULL, '1', '5', '4', '5', NULL, NULL, NULL, NULL, '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '12', '1', '1', '10', '4', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:23:58+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '46''', '小松 蓮', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138859', '1', '日本: J2 リーグ - ラウンド 18', '63:22', '18.', 'ブラウブリッツ秋田', '1', '13.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '40%', '60%', NULL, NULL, '1', '5', '4', '5', NULL, NULL, NULL, NULL, '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5', '12', '1', '1', '10', '4', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:27:02+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '46''', '小松 蓮', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138860', '1', '日本: J2 リーグ - ラウンド 18', '66:21', '18.', 'ブラウブリッツ秋田', '1', '14.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '40%', '60%', NULL, NULL, '1', '5', '4', '5', NULL, NULL, NULL, NULL, '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8', '14', '1', '1', '14', '6', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:30:03+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール通知対象', NULL, '46''', '小松 蓮', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138861', '1', '日本: J2 リーグ - ラウンド 18', '74:15', '16.', 'ブラウブリッツ秋田', '2', '17.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '42%', '58%', NULL, NULL, '2', '5', '6', '5', NULL, NULL, NULL, NULL, '6', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8', '14', '1', '1', '14', '6', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:37:55+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール非通知対象', NULL, '46''', '村松 航太', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138862', '1', '日本: J2 リーグ - ラウンド 18', '77:26', '16.', 'ブラウブリッツ秋田', '2', '17.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '40%', '60%', NULL, NULL, '2', '5', '6', '5', NULL, NULL, NULL, NULL, '6', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8', '14', '1', '1', '15', '6', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:41:06+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', NULL, NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール非通知対象', NULL, '46''', '村松 航太', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138863', '1', '日本: J2 リーグ - ラウンド 18', '80:29', '16.', 'ブラウブリッツ秋田', '2', '17.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '42%', '58%', NULL, NULL, '2', '5', '6', '5', NULL, NULL, NULL, NULL, '6', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8', '14', '1', '1', '15', '6', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:44:09+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', '4 266', NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール非通知対象', NULL, '46''', '村松 航太', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138864', '1', '日本: J2 リーグ - ラウンド 18', '87:34', '16.', 'ブラウブリッツ秋田', '2', '17.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '39%', '61%', NULL, NULL, '2', '5', '7', '6', NULL, NULL, NULL, NULL, '7', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8', '14', '1', '1', '15', '6', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 15:51:13+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', '4 266', NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '6', '11', '10', '9', '12', '20', '4', '8', 'メール非通知対象', NULL, '46''', '村松 航太', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('138865', '1', '日本: J2 リーグ - ラウンド 18', '終了済', '16.', 'ブラウブリッツ秋田', '2', '17.', 'カターレ富山', '2', NULL, NULL, NULL, NULL, '39%', '61%', NULL, NULL, '5', '5', '11', '6', NULL, NULL, NULL, NULL, '8', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11', '17', '1', '2', '18', '8', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-31 16:08:00+09', NULL, NULL, NULL, 'Nobori K. (Jpn)', '吉田 謙', '小田切 道治', NULL, NULL, 'ソユースタジアム (秋田)', '20 125', '4 266', NULL, '小松 蓮', '碓井 聖生', '出場中', '出場中', '8', '13', '10', '9', '12', '20', '6', '10', 'メール非通知対象', NULL, '46''', '村松 航太', NULL, 'プレッシング', 'プレッシング', 'AAAAAA', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('139275', '1', '日本: J2・J3 リーグ - ラウンド 21', '2:18', '11.', '北海道ｺﾝｻﾄﾞｰﾚ札幌', '0', '17.', 'ロアッソ熊本', '0', NULL, NULL, NULL, NULL, '74%', '26%', NULL, NULL, '0', '0', '0', '0', NULL, NULL, NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-06-28 14:07:59+09', NULL, NULL, NULL, 'Nakai T. (Jpn)', '岩政 大樹', '大木 武', NULL, NULL, '札幌厚別公園競技場 (札幌)', '20 861', NULL, NULL, 'A.バカヨコ', '塩浜 遼', '未出場', '未出場', '12', '14', '11', '17', '13', '18', '9', '13', 'メール通知対象', NULL, '---', '---', NULL, '---', '---', 'BBBBBB', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('139291', '1', '日本: J2・J3 リーグ - ラウンド 21', 'ハーフタイム', '12.', '北海道ｺﾝｻﾄﾞｰﾚ札幌', '0', '15.', 'ロアッソ熊本', '1', NULL, NULL, NULL, NULL, '63%', '37%', NULL, NULL, '3', '3', '3', '2', NULL, NULL, NULL, NULL, '4', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8', '1', '0', '1', '0', '5', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-06-28 14:56:05+09', NULL, NULL, NULL, 'Nakai T. (Jpn)', '岩政 大樹', '大木 武', NULL, NULL, '札幌厚別公園競技場 (札幌)', '20 861', NULL, NULL, 'A.バカヨコ', '塩浜 遼', '未出場', '未出場', '12', '14', '11', '17', '13', '18', '9', '13', 'メール通知対象', NULL, '---', '---', NULL, 'プレッシング', 'プレッシング', 'BBBBBB', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('139306', '1', '日本: J2・J3 リーグ - ラウンド 21', '94:46', '9.', '北海道ｺﾝｻﾄﾞｰﾚ札幌', '3', '17.', 'ロアッソ熊本', '2', NULL, NULL, NULL, NULL, '63%', '37%', NULL, NULL, '7', '6', '5', '6', NULL, NULL, NULL, NULL, '5', '9', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '16', '7', '0', '2', '7', '12', '2', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-06-28 15:59:03+09', NULL, NULL, NULL, 'Nakai T. (Jpn)', '岩政 大樹', '大木 武', NULL, NULL, '札幌厚別公園競技場 (札幌)', '20 861', '22 035', NULL, 'A.バカヨコ', '塩浜 遼', '未出場', '未出場', '12', '14', '11', '17', '13', '18', '9', '13', 'メール非通知対象', NULL, '64''', '高嶺 朋樹', NULL, 'プレッシング', 'プレッシング', 'BBBBBB', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('139421', '1', '日本: J2・J3 リーグ - ラウンド 21', '終了済', '16.', '北海道ｺﾝｻﾄﾞｰﾚ札幌', '2', '10.', 'ロアッソ熊本', '2', NULL, NULL, NULL, NULL, '58%', '42%', NULL, NULL, '3', '4', '13', '7', NULL, NULL, NULL, NULL, '6', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15', '3', '2', '3', '13', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-06-28 16:09:21+09', NULL, NULL, NULL, 'Ohashi Y. (Jpn)', '岩政 大樹', '下平 隆宏', NULL, NULL, '札幌厚別公園競技場 (札幌)', '20 861', '18 028', NULL, '近藤 友喜', 'M.ジェズス', '出場中', '未出場', '6', '7', '13', '9', '6', '13', '9', '13', 'メール非通知対象', NULL, '55''', '原 康介', NULL, 'プレッシング', 'プレッシング', 'BBBBBB', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
    ('119022',
    '1',
    'ブラジル: セリエ A ベターノ - ラウンド 11',
    '31:58',
    '6.',
    'バイーア',
    '0',
    '11.',
    'サンパウロ',
    '0',
    '0.07',
    '0.16',
    NULL,
    NULL,
    '76%',
    '24%',
    NULL,
    NULL,
    '1',
    '0',
    '0',
    '1',
    NULL,
    NULL,
    '0',
    '0',
    '3',
    '1',
    '1',
    '0',
    '2',
    '1',
    '0',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    '4',
    '1',
    '2',
    '0',
    '1',
    '4',
    NULL,
    NULL,
    NULL,
    NULL,
    '8',
    '3',
    '5',
    '1',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '2025-06-01 07:02:45+09',
    NULL,
    NULL,
    NULL,
    'Daronco A. (Bra)',
    'Rogerio Ceni',
    'Zubeldia Luis Francisco',
    NULL,
    NULL,
    'アレナ フォンテ ノヴァ (サルヴァドール)',
    '48 902',
    NULL,
    NULL,
    'Erick Pulga',
    'A.シウヴァ',
    '未出場',
    '未出場',
    '6',
    '3',
    '5',
    '5',
    '3',
    '7',
    '3',
    '4',
    NULL,
    '未通知',
    NULL,
    '---',
    '---',
    'メール通知対象',
    'プレッシング',
    'プレッシング',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '0',
    'bm_user',
    '2026-01-16 13:12:15+09',
    'bm_user',
    '2026-01-16 13:12:15+09');

INSERT INTO csv_detail_manage (
    id,
    csv_id,
    data_category,
    season,
    home_team_name,
    away_team_name,
    check_fin_flg,
    register_id,
    register_time,
    update_id,
    update_time
) VALUES
	('1', '日本-J2 リーグ - ラウンド 18/1.csv', '日本: J2 リーグ - ラウンド 18', '2026', 'ブラウブリッツ秋田', 'カターレ富山', '0',  NULL, NULL, NULL, NULL),
	('2', 'ブラジル-セリエ A ベターノ - ラウンド 18/1.csv', 'ブラジル: セリエ A ベターノ - ラウンド 18', '2026', 'レッドブル・ブラガンチーノ', 'バイーア', '0',  NULL, NULL, NULL, NULL),
	('3', '日本-J2・J3 リーグ - ラウンド 21/1.csv', '日本: J2・J3 リーグ - ラウンド 21', '2026', '北海道ｺﾝｻﾄﾞｰﾚ札幌', 'ロアッソ熊本', '0',  NULL, NULL, NULL, NULL);
