-- =========================
-- prisma-master (H2)
-- =========================

-- -------------------------
-- team_member_master
-- -------------------------
CREATE TABLE IF NOT EXISTS team_member_master (
  id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  country                VARCHAR(255),
  league                 VARCHAR(255),

  team                   VARCHAR(255) NOT NULL,
  score                  VARCHAR(50),
  loan_belong            VARCHAR(255),

  jersey                 VARCHAR(50) NOT NULL,
  member                 VARCHAR(255) NOT NULL,
  face_pic_path          VARCHAR(1024) NOT NULL,

  belong_list            CLOB,
  height                 VARCHAR(255),
  weight                 VARCHAR(255),
  position               VARCHAR(255),
  birth                  VARCHAR(50),
  age                    VARCHAR(50),
  market_value           VARCHAR(255),
  injury                 CLOB,
  versus_team_score_data CLOB,

  retire_flg             CHAR(1),
  deadline               CHAR(1),
  deadline_contract_date VARCHAR(255),
  latest_info_date       VARCHAR(50),
  upd_stamp              VARCHAR(255),
  del_flg                CHAR(1),

  register_id            VARCHAR(100) NOT NULL,
  register_time          TIMESTAMP WITH TIME ZONE NOT NULL,
  update_id              VARCHAR(100) NOT NULL,
  update_time            TIMESTAMP WITH TIME ZONE NOT NULL
);

-- UNIQUE制約（H2でOK）
CREATE UNIQUE INDEX IF NOT EXISTS uk_team_member_master
  ON team_member_master(team, jersey, member, face_pic_path);

-- -------------------------
-- country_league_master
-- -------------------------
CREATE TABLE IF NOT EXISTS country_league_master (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country       VARCHAR(255) NOT NULL,
  league        VARCHAR(255) NOT NULL,
  team          VARCHAR(255) NOT NULL,
  link          VARCHAR(2048) NOT NULL,
  del_flg       CHAR(1),
  register_id   VARCHAR(100) NOT NULL,
  register_time TIMESTAMP WITH TIME ZONE NOT NULL,
  update_id     VARCHAR(100) NOT NULL,
  update_time   TIMESTAMP WITH TIME ZONE NOT NULL
);

-- -------------------------
-- country_league_season_master
-- -------------------------
CREATE TABLE IF NOT EXISTS country_league_season_master (
  id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country           VARCHAR(255) NOT NULL,
  league            VARCHAR(255) NOT NULL,
  season_year       VARCHAR(50) NOT NULL,
  start_season_date TIMESTAMP WITH TIME ZONE,
  end_season_date   TIMESTAMP WITH TIME ZONE,
  round             VARCHAR(2),
  path              VARCHAR(2048),
  icon              VARCHAR(2048),
  valid_flg         VARCHAR(1) DEFAULT '0' NOT NULL,
  del_flg           CHAR(1),
  register_id       VARCHAR(100),
  register_time     TIMESTAMP WITH TIME ZONE,
  update_id         VARCHAR(100),
  update_time       TIMESTAMP WITH TIME ZONE
);

-- -------------------------
-- team_color_master
-- -------------------------
CREATE TABLE IF NOT EXISTS team_color_master (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country         VARCHAR(255) NOT NULL,
  league          VARCHAR(255) NOT NULL,
  team            VARCHAR(255) NOT NULL,
  team_color_hex  VARCHAR(7),
  register_id     VARCHAR(100),
  register_time   TIMESTAMP WITH TIME ZONE,
  update_id       VARCHAR(100),
  update_time     TIMESTAMP WITH TIME ZONE
);

-- -------------------------
-- future_master
-- -------------------------
CREATE TABLE IF NOT EXISTS future_master (
  seq                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_team_category      VARCHAR(255) NOT NULL,
  future_time             TIMESTAMP WITH TIME ZONE NOT NULL,

  home_rank               VARCHAR(50),
  away_rank               VARCHAR(50),
  home_team_name          VARCHAR(255),
  away_team_name          VARCHAR(255),

  home_max_getting_scorer VARCHAR(255),
  away_max_getting_scorer VARCHAR(255),

  home_team_home_score    VARCHAR(50),
  home_team_home_lost     VARCHAR(50),
  away_team_home_score    VARCHAR(50),
  away_team_home_lost     VARCHAR(50),
  home_team_away_score    VARCHAR(50),
  home_team_away_lost     VARCHAR(50),
  away_team_away_score    VARCHAR(50),
  away_team_away_lost     VARCHAR(50),

  game_link               VARCHAR(2048),
  data_time               TIMESTAMP WITH TIME ZONE,
  start_flg               VARCHAR(1) DEFAULT '0' NOT NULL,

  register_id             VARCHAR(100),
  register_time           TIMESTAMP WITH TIME ZONE,
  update_id               VARCHAR(100),
  update_time             TIMESTAMP WITH TIME ZONE
);
