-- src/test/resources/schema-bm.sql (H2)

CREATE SCHEMA IF NOT EXISTS soccer_bm;
SET SCHEMA soccer_bm;

DROP TABLE IF EXISTS data;
DROP SEQUENCE IF EXISTS data_seq_seq;

CREATE SEQUENCE data_seq_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE data (
  seq INT NOT NULL DEFAULT NEXT VALUE FOR data_seq_seq,

  condition_result_data_seq_id VARCHAR(3),
  data_category VARCHAR,
  times VARCHAR,
  home_rank VARCHAR,
  home_team_name VARCHAR,
  home_score VARCHAR DEFAULT '0',
  away_rank VARCHAR,
  away_team_name VARCHAR,
  away_score VARCHAR DEFAULT '0',
  home_exp VARCHAR,
  away_exp VARCHAR,
  home_in_goal_exp VARCHAR,
  away_in_goal_exp VARCHAR,
  home_donation VARCHAR,
  away_donation VARCHAR,
  home_shoot_all VARCHAR,
  away_shoot_all VARCHAR,
  home_shoot_in VARCHAR,
  away_shoot_in VARCHAR,
  home_shoot_out VARCHAR,
  away_shoot_out VARCHAR,
  home_block_shoot VARCHAR,
  away_block_shoot VARCHAR,
  home_big_chance VARCHAR,
  away_big_chance VARCHAR,
  home_corner VARCHAR,
  away_corner VARCHAR,
  home_box_shoot_in VARCHAR,
  away_box_shoot_in VARCHAR,
  home_box_shoot_out VARCHAR,
  away_box_shoot_out VARCHAR,
  home_goal_post VARCHAR,
  away_goal_post VARCHAR,
  home_goal_head VARCHAR,
  away_goal_head VARCHAR,
  home_keeper_save VARCHAR,
  away_keeper_save VARCHAR,
  home_free_kick VARCHAR,
  away_free_kick VARCHAR,
  home_offside VARCHAR,
  away_offside VARCHAR,
  home_foul VARCHAR,
  away_foul VARCHAR,
  home_yellow_card VARCHAR,
  away_yellow_card VARCHAR,
  home_red_card VARCHAR,
  away_red_card VARCHAR,
  home_slow_in VARCHAR,
  away_slow_in VARCHAR,
  home_box_touch VARCHAR,
  away_box_touch VARCHAR,
  home_pass_count VARCHAR,
  away_pass_count VARCHAR,
  home_long_pass_count VARCHAR,
  away_long_pass_count VARCHAR,
  home_final_third_pass_count VARCHAR,
  away_final_third_pass_count VARCHAR,
  home_cross_count VARCHAR,
  away_cross_count VARCHAR,
  home_tackle_count VARCHAR,
  away_tackle_count VARCHAR,
  home_clear_count VARCHAR,
  away_clear_count VARCHAR,
  home_duel_count VARCHAR,
  away_duel_count VARCHAR,
  home_intercept_count VARCHAR,
  away_intercept_count VARCHAR,

  record_time TIMESTAMP WITH TIME ZONE,
  weather VARCHAR,
  temparature VARCHAR,
  humid VARCHAR,
  judge_member VARCHAR,
  home_manager VARCHAR,
  away_manager VARCHAR,
  home_formation VARCHAR,
  away_formation VARCHAR,
  studium VARCHAR,
  capacity VARCHAR,
  audience VARCHAR,
  home_max_getting_scorer VARCHAR,
  away_max_getting_scorer VARCHAR,
  home_max_getting_scorer_game_situation VARCHAR,
  away_max_getting_scorer_game_situation VARCHAR,
  home_team_home_score VARCHAR,
  home_team_home_lost VARCHAR,
  away_team_home_score VARCHAR,
  away_team_home_lost VARCHAR,
  home_team_away_score VARCHAR,
  home_team_away_lost VARCHAR,
  away_team_away_score VARCHAR,
  away_team_away_lost VARCHAR,
  notice_flg VARCHAR,
  goal_time VARCHAR,
  goal_team_member VARCHAR,
  judge VARCHAR,
  home_team_style VARCHAR,
  away_team_style VARCHAR,
  probablity VARCHAR,
  prediction_score_time VARCHAR,

  register_id VARCHAR(100),
  register_time TIMESTAMP WITH TIME ZONE,
  update_id VARCHAR(100),
  update_time TIMESTAMP WITH TIME ZONE,

  CONSTRAINT data_pkey PRIMARY KEY (seq)
);

CREATE INDEX idx_data_keys_times_seq
  ON data (data_category, home_team_name, away_team_name, times, seq);
