package dev.application.domain.repository;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;

import dev.application.analyze.bm_m024.CalcCorrelationEntity;

@Mapper
public interface CalcCorrelationRepository {

    @Insert({
        "INSERT INTO correlation_data (",
        "id, file, country, league, home, away, score, chk_body,",
        "home_exp_info, away_exp_info,",
        "home_donation_info, away_donation_info,",
        "home_shoot_all_info, away_shoot_all_info,",
        "home_shoot_in_info, away_shoot_in_info,",
        "home_shoot_out_info, away_shoot_out_info,",
        "home_block_shoot_info, away_block_shoot_info,",
        "home_big_chance_info, away_big_chance_info,",
        "home_corner_info, away_corner_info,",
        "home_box_shoot_in_info, away_box_shoot_in_info,",
        "home_box_shoot_out_info, away_box_shoot_out_info,",
        "home_goal_post_info, away_goal_post_info,",
        "home_goal_head_info, away_goal_head_info,",
        "home_keeper_save_info, away_keeper_save_info,",
        "home_free_kick_info, away_free_kick_info",
        "home_offside_info, away_offside_info",
        "home_foul_info, away_foul_info",
        "home_yellow_card_info, away_yellow_card_info",
        "home_red_card_info, away_red_card_info",
        "home_slow_in_info, away_slow_in_info",
        "home_box_touch_info, away_box_touch_info",
        "home_pass_count_info_on_success_ratio",
        "home_pass_count_info_on_success_count",
        "home_pass_count_info_on_try_count",
        "away_pass_count_info_on_success_ratio",
        "away_pass_count_info_on_success_count",
        "away_pass_count_info_on_try_count",
        "home_final_third_pass_count_info_on_success_ratio",
        "home_final_third_pass_count_info_on_success_count",
        "home_final_third_pass_count_info_on_try_count",
        "away_final_third_pass_count_info_on_success_ratio",
        "away_final_third_pass_count_info_on_success_count",
        "away_final_third_pass_count_info_on_try_count",
        "home_cross_count_info_on_success_ratio",
        "home_cross_count_info_on_success_count",
        "home_cross_count_info_on_try_count",
        "away_cross_count_info_on_success_ratio",
        "away_cross_count_info_on_success_count",
        "away_cross_count_info_on_try_count",
        "home_tackle_count_info_on_success_ratio",
        "home_tackle_count_info_on_success_count",
        "home_tackle_count_info_on_try_count",
        "away_tackle_count_info_on_success_ratio",
        "away_tackle_count_info_on_success_count",
        "away_tackle_count_info_on_try_count",
        "home_clear_count_info",
        "away_clear_count_info",
        "home_intercept_count_info",
        "away_intercept_count_info",
        "register_id, register_time, update_id, update_time",
        ") VALUES (",
        "#{id}, #{file}, #{country}, #{league}, #{home}, #{away}, #{score}, #{chkBody},",
        "#{homeExpInfo}, #{awayExpInfo},",
        "#{homeDonationInfo}, #{awayDonationInfo},",
        "#{homeShootAllInfo}, #{awayShootAllInfo},",
        "#{homeShootInInfo}, #{awayShootInInfo},",
        "#{homeShootOutInfo}, #{awayShootOutInfo},",
        "#{homeBlockShootInfo}, #{awayBlockShootInfo},",
        "#{homeBigChanceInfo}, #{awayBigChanceInfo},",
        "#{homeCornerInfo}, #{awayCornerInfo},",
        "#{homeBoxShootInInfo}, #{awayBoxShootInInfo},",
        "#{homeBoxShootOutInfo}, #{awayBoxShootOutInfo},",
        "#{homeGoalPostInfo}, #{awayGoalPostInfo},",
        "#{homeGoalHeadInfo}, #{awayGoalHeadInfo},",
        "#{homeKeeperSaveInfo}, #{awayKeeperSaveInfo},",
        "#{homeFreeKickInfo}, #{awayFreeKickInfo}",
        "#{homeOffsideInfo}, #{awayOffsideInfo},",
        "#{homeFoulInfo}, #{awayFoulInfo},",
        "#{homeYellowCardInfo}, #{awayYellowCardInfo},",
        "#{homeRedCardInfo}, #{awayRedCardInfo},",
        "#{homeSlowInInfo}, #{awaySlowInInfo},",
        "#{homeBoxTouchInfo}, #{awayBoxTouchInfo},",
        "#{homePassCountInfoOnSuccessRatio}, #{homePassCountInfoOnSuccessCount}, #{homePassCountInfoOnTryCount},",
        "#{awayPassCountInfoOnSuccessRatio}, #{awayPassCountInfoOnSuccessCount}, #{awayPassCountInfoOnTryCount},",
        "#{homeFinalThirdPassCountInfoOnSuccessRatio}, #{homeFinalThirdPassCountInfoOnSuccessCount}, #{homeFinalThirdPassCountInfoOnTryCount},",
        "#{awayFinalThirdPassCountInfoOnSuccessRatio}, #{awayFinalThirdPassCountInfoOnSuccessCount}, #{awayFinalThirdPassCountInfoOnTryCount},",
        "#{homeCrossCountInfoOnSuccessRatio}, #{homeCrossCountInfoOnSuccessCount}, #{homeCrossCountInfoOnTryCount},",
        "#{awayCrossCountInfoOnSuccessRatio}, #{awayCrossCountInfoOnSuccessCount}, #{awayCrossCountInfoOnTryCount},",
        "#{homeTackleCountInfoOnSuccessRatio}, #{homeTackleCountInfoOnSuccessCount},#{homeTackleCountInfoOnTryCount}, ",
        "#{awayTackleCountInfoOnSuccessRatio},#{awayTackleCountInfoOnSuccessCount}, #{awayTackleCountInfoOnTryCount},",
        "#{homeClearCountInfo}, #{awayClearCountInfo},",
        "#{homeInterceptCountInfo}, #{awayInterceptCountInfo},",
        "#{registerId}, #{registerTime}, #{updateId}, #{updateTime}",
        ")"
    })
    void insert(CalcCorrelationEntity entity);
}
