package dev.application.domain.repository.bm;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import dev.application.analyze.bm_m024.CalcCorrelationEntity;

@Mapper
public interface CalcCorrelationRepository {

    @Insert({
        "INSERT INTO calc_correlation (",
        "file, country, league, home, away, score, chk_body,",
        "home_exp_info, away_exp_info,",
        "home_in_goal_exp_info, away_in_goal_exp_info,",
        "home_donation_info, away_donation_info,",
        "home_shoot_all_info, away_shoot_all_info,",
        "home_shoot_in_info, away_shoot_in_info,",
        "home_shoot_out_info, away_shoot_out_info,",
        "home_block_shoot_info, away_block_shoot_info,",
        "home_big_chance_info, away_big_chance_info,",
        "home_corner_info, away_corner_info,",
        "home_box_shoot_in_info, away_box_shoot_in_info,",
        "home_box_shoot_out_info, away_box_shoot_out_info,",
        "home_goal_post_info, away_goal_post_info,",
        "home_goal_head_info, away_goal_head_info,",
        "home_keeper_save_info, away_keeper_save_info,",
        "home_free_kick_info, away_free_kick_info,",
        "home_offside_info, away_offside_info,",
        "home_foul_info, away_foul_info,",
        "home_yellow_card_info, away_yellow_card_info,",
        "home_red_card_info, away_red_card_info,",
        "home_slow_in_info, away_slow_in_info,",
        "home_box_touch_info, away_box_touch_info,",
        "home_pass_count_info_on_success_ratio,",
        "home_pass_count_info_on_success_count,",
        "home_pass_count_info_on_try_count,",
        "away_pass_count_info_on_success_ratio,",
        "away_pass_count_info_on_success_count,",
        "away_pass_count_info_on_try_count,",
        "home_final_third_pass_count_info_on_success_ratio,",
        "home_final_third_pass_count_info_on_success_count,",
        "home_final_third_pass_count_info_on_try_count,",
        "away_final_third_pass_count_info_on_success_ratio,",
        "away_final_third_pass_count_info_on_success_count,",
        "away_final_third_pass_count_info_on_try_count,",
        "home_cross_count_info_on_success_ratio,",
        "home_cross_count_info_on_success_count,",
        "home_cross_count_info_on_try_count,",
        "away_cross_count_info_on_success_ratio,",
        "away_cross_count_info_on_success_count,",
        "away_cross_count_info_on_try_count,",
        "home_tackle_count_info_on_success_ratio,",
        "home_tackle_count_info_on_success_count,",
        "home_tackle_count_info_on_try_count,",
        "away_tackle_count_info_on_success_ratio,",
        "away_tackle_count_info_on_success_count,",
        "away_tackle_count_info_on_try_count,",
        "home_clear_count_info,",
        "away_clear_count_info,",
        "home_intercept_count_info,",
        "away_intercept_count_info,",
        "register_id, register_time, update_id, update_time",
        ") VALUES (",
        "#{file}, #{country}, #{league}, #{home}, #{away}, #{score}, #{chkBody},",
        "#{homeExpInfo}, #{awayExpInfo},",
        "#{homeInGoalExpInfo}, #{awayInGoalExpInfo},",
        "#{homeDonationInfo}, #{awayDonationInfo},",
        "#{homeShootAllInfo}, #{awayShootAllInfo},",
        "#{homeShootInInfo}, #{awayShootInInfo},",
        "#{homeShootOutInfo}, #{awayShootOutInfo},",
        "#{homeBlockShootInfo}, #{awayBlockShootInfo},",
        "#{homeBigChanceInfo}, #{awayBigChanceInfo},",
        "#{homeCornerInfo}, #{awayCornerInfo},",
        "#{homeBoxShootInInfo}, #{awayBoxShootInInfo},",
        "#{homeBoxShootOutInfo}, #{awayBoxShootOutInfo},",
        "#{homeGoalPostInfo}, #{awayGoalPostInfo},",
        "#{homeGoalHeadInfo}, #{awayGoalHeadInfo},",
        "#{homeKeeperSaveInfo}, #{awayKeeperSaveInfo},",
        "#{homeFreeKickInfo}, #{awayFreeKickInfo},",
        "#{homeOffsideInfo}, #{awayOffsideInfo},",
        "#{homeFoulInfo}, #{awayFoulInfo},",
        "#{homeYellowCardInfo}, #{awayYellowCardInfo},",
        "#{homeRedCardInfo}, #{awayRedCardInfo},",
        "#{homeSlowInInfo}, #{awaySlowInInfo},",
        "#{homeBoxTouchInfo}, #{awayBoxTouchInfo},",
        "#{homePassCountInfoOnSuccessRatio}, #{homePassCountInfoOnSuccessCount}, #{homePassCountInfoOnTryCount},",
        "#{awayPassCountInfoOnSuccessRatio}, #{awayPassCountInfoOnSuccessCount}, #{awayPassCountInfoOnTryCount},",
        "#{homeFinalThirdPassCountInfoOnSuccessRatio}, #{homeFinalThirdPassCountInfoOnSuccessCount}, #{homeFinalThirdPassCountInfoOnTryCount},",
        "#{awayFinalThirdPassCountInfoOnSuccessRatio}, #{awayFinalThirdPassCountInfoOnSuccessCount}, #{awayFinalThirdPassCountInfoOnTryCount},",
        "#{homeCrossCountInfoOnSuccessRatio}, #{homeCrossCountInfoOnSuccessCount}, #{homeCrossCountInfoOnTryCount},",
        "#{awayCrossCountInfoOnSuccessRatio}, #{awayCrossCountInfoOnSuccessCount}, #{awayCrossCountInfoOnTryCount},",
        "#{homeTackleCountInfoOnSuccessRatio}, #{homeTackleCountInfoOnSuccessCount}, #{homeTackleCountInfoOnTryCount},",
        "#{awayTackleCountInfoOnSuccessRatio}, #{awayTackleCountInfoOnSuccessCount}, #{awayTackleCountInfoOnTryCount},",
        "#{homeClearCountInfo}, #{awayClearCountInfo},",
        "#{homeInterceptCountInfo}, #{awayInterceptCountInfo},",
        "#{registerId}, CAST(#{registerTime} AS timestamptz), #{updateId}, CAST(#{updateTime}  AS timestamptz)",
        ");"
    })
    int insert(CalcCorrelationEntity entity);

    @Select({
        "SELECT ",
        "id,",
        "home_exp_info, away_exp_info,",
        "home_donation_info, away_donation_info,",
        "home_shoot_all_info, away_shoot_all_info,",
        "home_shoot_in_info, away_shoot_in_info,",
        "home_shoot_out_info, away_shoot_out_info,",
        "home_block_shoot_info, away_block_shoot_info,",
        "home_big_chance_info, away_big_chance_info,",
        "home_corner_info, away_corner_info,",
        "home_box_shoot_in_info, away_box_shoot_in_info,",
        "home_box_shoot_out_info, away_box_shoot_out_info,",
        "home_goal_post_info, away_goal_post_info,",
        "home_goal_head_info, away_goal_head_info,",
        "home_keeper_save_info, away_keeper_save_info,",
        "home_free_kick_info, away_free_kick_info,",
        "home_offside_info, away_offside_info,",
        "home_foul_info, away_foul_info,",
        "home_yellow_card_info, away_yellow_card_info,",
        "home_red_card_info, away_red_card_info,",
        "home_slow_in_info, away_slow_in_info,",
        "home_box_touch_info, away_box_touch_info,",
        "home_pass_count_info_on_success_ratio,",
        "home_pass_count_info_on_success_count,",
        "home_pass_count_info_on_try_count,",
        "away_pass_count_info_on_success_ratio,",
        "away_pass_count_info_on_success_count,",
        "away_pass_count_info_on_try_count,",
        "home_final_third_pass_count_info_on_success_ratio,",
        "home_final_third_pass_count_info_on_success_count,",
        "home_final_third_pass_count_info_on_try_count,",
        "away_final_third_pass_count_info_on_success_ratio,",
        "away_final_third_pass_count_info_on_success_count,",
        "away_final_third_pass_count_info_on_try_count,",
        "home_cross_count_info_on_success_ratio,",
        "home_cross_count_info_on_success_count,",
        "home_cross_count_info_on_try_count,",
        "away_cross_count_info_on_success_ratio,",
        "away_cross_count_info_on_success_count,",
        "away_cross_count_info_on_try_count,",
        "home_tackle_count_info_on_success_ratio,",
        "home_tackle_count_info_on_success_count,",
        "home_tackle_count_info_on_try_count,",
        "away_tackle_count_info_on_success_ratio,",
        "away_tackle_count_info_on_success_count,",
        "away_tackle_count_info_on_try_count,",
        "home_clear_count_info,",
        "away_clear_count_info,",
        "home_intercept_count_info,",
        "away_intercept_count_info",
        " FROM calc_correlation ",
        " WHERE ",
        "country = #{country} AND"
        + " league = #{league} AND"
        + " home = #{home} AND"
        + " away = #{away} AND"
        + " score = #{score} AND"
        + " chk_body = #{chkBody};"
    })
    List<CalcCorrelationEntity> findStatData(String country, String league, String home,
    		String away, String score, String chkBody);

    @Update({
        "UPDATE calc_correlation SET",
        "home_exp_info = #{homeExpInfo},",
        "away_exp_info = #{awayExpInfo},",
        "home_donation_info = #{homeDonationInfo},",
        "away_donation_info = #{awayDonationInfo},",
        "home_shoot_all_info = #{homeShootAllInfo},",
        "away_shoot_all_info = #{awayShootAllInfo},",
        "home_shoot_in_info = #{homeShootInInfo},",
        "away_shoot_in_info = #{awayShootInInfo},",
        "home_shoot_out_info = #{homeShootOutInfo},",
        "away_shoot_out_info = #{awayShootOutInfo},",
        "home_block_shoot_info = #{homeBlockShootInfo},",
        "away_block_shoot_info = #{awayBlockShootInfo},",
        "home_big_chance_info = #{homeBigChanceInfo},",
        "away_big_chance_info = #{awayBigChanceInfo},",
        "home_corner_info = #{homeCornerInfo},",
        "away_corner_info = #{awayCornerInfo},",
        "home_box_shoot_in_info = #{homeBoxShootInInfo},",
        "away_box_shoot_in_info = #{awayBoxShootInInfo},",
        "home_box_shoot_out_info = #{homeBoxShootOutInfo},",
        "away_box_shoot_out_info = #{awayBoxShootOutInfo},",
        "home_goal_post_info = #{homeGoalPostInfo},",
        "away_goal_post_info = #{awayGoalPostInfo},",
        "home_goal_head_info = #{homeGoalHeadInfo},",
        "away_goal_head_info = #{awayGoalHeadInfo},",
        "home_keeper_save_info = #{homeKeeperSaveInfo},",
        "away_keeper_save_info = #{awayKeeperSaveInfo},",
        "home_free_kick_info = #{homeFreeKickInfo},",
        "away_free_kick_info = #{awayFreeKickInfo},",
        "home_offside_info = #{homeOffsideInfo},",
        "away_offside_info = #{awayOffsideInfo},",
        "home_foul_info = #{homeFoulInfo},",
        "away_foul_info = #{awayFoulInfo},",
        "home_yellow_card_info = #{homeYellowCardInfo},",
        "away_yellow_card_info = #{awayYellowCardInfo},",
        "home_red_card_info = #{homeRedCardInfo},",
        "away_red_card_info = #{awayRedCardInfo},",
        "home_slow_in_info = #{homeSlowInInfo},",
        "away_slow_in_info = #{awaySlowInInfo},",
        "home_box_touch_info = #{homeBoxTouchInfo},",
        "away_box_touch_info = #{awayBoxTouchInfo},",
        "home_pass_count_info_on_success_ratio = #{homePassCountInfoOnSuccessRatio},",
        "home_pass_count_info_on_success_count = #{homePassCountInfoOnSuccessCount},",
        "home_pass_count_info_on_try_count = #{homePassCountInfoOnTryCount},",
        "away_pass_count_info_on_success_ratio = #{awayPassCountInfoOnSuccessRatio},",
        "away_pass_count_info_on_success_count = #{awayPassCountInfoOnSuccessCount},",
        "away_pass_count_info_on_try_count = #{awayPassCountInfoOnTryCount},",
        "home_final_third_pass_count_info_on_success_ratio = #{homeFinalThirdPassCountInfoOnSuccessRatio},",
        "home_final_third_pass_count_info_on_success_count = #{homeFinalThirdPassCountInfoOnSuccessCount},",
        "home_final_third_pass_count_info_on_try_count = #{homeFinalThirdPassCountInfoOnTryCount},",
        "away_final_third_pass_count_info_on_success_ratio = #{awayFinalThirdPassCountInfoOnSuccessRatio},",
        "away_final_third_pass_count_info_on_success_count = #{awayFinalThirdPassCountInfoOnSuccessCount},",
        "away_final_third_pass_count_info_on_try_count = #{awayFinalThirdPassCountInfoOnTryCount},",
        "home_cross_count_info_on_success_ratio = #{homeCrossCountInfoOnSuccessRatio},",
        "home_cross_count_info_on_success_count = #{homeCrossCountInfoOnSuccessCount},",
        "home_cross_count_info_on_try_count = #{homeCrossCountInfoOnTryCount},",
        "away_cross_count_info_on_success_ratio = #{awayCrossCountInfoOnSuccessRatio},",
        "away_cross_count_info_on_success_count = #{awayCrossCountInfoOnSuccessCount},",
        "away_cross_count_info_on_try_count = #{awayCrossCountInfoOnTryCount},",
        "home_tackle_count_info_on_success_ratio = #{homeTackleCountInfoOnSuccessRatio},",
        "home_tackle_count_info_on_success_count = #{homeTackleCountInfoOnSuccessCount},",
        "home_tackle_count_info_on_try_count = #{homeTackleCountInfoOnTryCount},",
        "away_tackle_count_info_on_success_ratio = #{awayTackleCountInfoOnSuccessRatio},",
        "away_tackle_count_info_on_success_count = #{awayTackleCountInfoOnSuccessCount},",
        "away_tackle_count_info_on_try_count = #{awayTackleCountInfoOnTryCount},",
        "home_clear_count_info = #{homeClearCountInfo},",
        "away_clear_count_info = #{awayClearCountInfo},",
        "home_intercept_count_info = #{homeInterceptCountInfo},",
        "away_intercept_count_info = #{awayInterceptCountInfo} ",
        "WHERE id = CAST(#{id,jdbcType=VARCHAR} AS INTEGER);"
    })
    int updateStatValues(CalcCorrelationEntity entity);

}
