package dev.application.domain.repository.bm;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Update;

import dev.application.analyze.bm_m029.RealDataProcessEntity;

@Mapper
public interface RealDataProcessRepository {

	@Insert("""
			INSERT INTO real_data_process (
			    condition_result_data_seq_id,
			    data_category,
			    times,
			    home_rank,
			    away_rank,
			    home_team_name,
			    away_team_name,
			    home_score,
			    away_score,
			    home_exp,
			    away_exp,
			    home_in_goal_exp,
			    away_in_goal_exp,
			    home_donation,
			    away_donation,
			    home_shoot_all,
			    away_shoot_all,
			    home_shoot_in,
			    away_shoot_in,
			    home_shoot_out,
			    away_shoot_out,
			    home_block_shoot,
			    away_block_shoot,
			    home_big_chance,
			    away_big_chance,
			    home_corner,
			    away_corner,
			    home_box_shoot_in,
			    away_box_shoot_in,
			    home_box_shoot_out,
			    away_box_shoot_out,
			    home_goal_post,
			    away_goal_post,
			    home_goal_head,
			    away_goal_head,
			    home_keeper_save,
			    away_keeper_save,
			    home_free_kick,
			    away_free_kick,
			    home_offside,
			    away_offside,
			    home_foul,
			    away_foul,
			    home_yellow_card,
			    away_yellow_card,
			    home_red_card,
			    away_red_card,
			    home_slow_in,
			    away_slow_in,
			    home_box_touch,
			    away_box_touch,
			    home_pass_count,
			    away_pass_count,
			    home_long_pass_count,
			    away_long_pass_count,
			    home_final_third_pass_count,
			    away_final_third_pass_count,
			    home_cross_count,
			    away_cross_count,
			    home_tackle_count,
			    away_tackle_count,
			    home_clear_count,
			    away_clear_count,
			    home_duel_count,
			    away_duel_count,
			    home_intercept_count,
			    away_intercept_count,
			    record_time,
			    weather,
			    temparature,
			    humid,
			    judge_member,
			    home_manager,
			    away_manager,
			    home_formation,
			    away_formation,
			    studium,
			    capacity,
			    audience,
			    location,
			    home_max_getting_scorer,
			    away_max_getting_scorer,
			    home_max_getting_scorer_game_situation,
			    away_max_getting_scorer_game_situation,
			    home_team_home_score,
			    home_team_home_lost,
			    away_team_home_score,
			    away_team_home_lost,
			    home_team_away_score,
			    home_team_away_lost,
			    away_team_away_score,
			    away_team_away_lost,
			    notice_flg,
			    game_link,
			    goal_time,
			    goal_team_member,
			    judge,
			    home_team_style,
			    away_team_style,
			    probablity,
			    prediction_score_time,
			    game_id,
			    match_id,
			    time_sort_seconds,
			    register_id,
			    register_time,
			    update_id,
			    update_time
			) VALUES (
			    #{conditionResultDataSeqId},
			    #{dataCategory},
			    #{times},
			    #{homeRank},
			    #{awayRank},
			    #{homeTeamName},
			    #{awayTeamName},
			    #{homeScore},
			    #{awayScore},
			    #{homeExp},
			    #{awayExp},
			    #{homeInGoalExp},
			    #{awayInGoalExp},
			    #{homeDonation},
			    #{awayDonation},
			    #{homeShootAll},
			    #{awayShootAll},
			    #{homeShootIn},
			    #{awayShootIn},
			    #{homeShootOut},
			    #{awayShootOut},
			    #{homeBlockShoot},
			    #{awayBlockShoot},
			    #{homeBigChance},
			    #{awayBigChance},
			    #{homeCorner},
			    #{awayCorner},
			    #{homeBoxShootIn},
			    #{awayBoxShootIn},
			    #{homeBoxShootOut},
			    #{awayBoxShootOut},
			    #{homeGoalPost},
			    #{awayGoalPost},
			    #{homeGoalHead},
			    #{awayGoalHead},
			    #{homeKeeperSave},
			    #{awayKeeperSave},
			    #{homeFreeKick},
			    #{awayFreeKick},
			    #{homeOffside},
			    #{awayOffside},
			    #{homeFoul},
			    #{awayFoul},
			    #{homeYellowCard},
			    #{awayYellowCard},
			    #{homeRedCard},
			    #{awayRedCard},
			    #{homeSlowIn},
			    #{awaySlowIn},
			    #{homeBoxTouch},
			    #{awayBoxTouch},
			    #{homePassCount},
			    #{awayPassCount},
			    #{homeLongPassCount},
			    #{awayLongPassCount},
			    #{homeFinalThirdPassCount},
			    #{awayFinalThirdPassCount},
			    #{homeCrossCount},
			    #{awayCrossCount},
			    #{homeTackleCount},
			    #{awayTackleCount},
			    #{homeClearCount},
			    #{awayClearCount},
			    #{homeDuelCount},
			    #{awayDuelCount},
			    #{homeInterceptCount},
			    #{awayInterceptCount},
			    CAST(#{recordTime} AS timestamptz),
			    #{weather},
			    #{temparature},
			    #{humid},
			    #{judgeMember},
			    #{homeManager},
			    #{awayManager},
			    #{homeFormation},
			    #{awayFormation},
			    #{studium},
			    #{capacity},
			    #{audience},
			    #{location},
			    #{homeMaxGettingScorer},
			    #{awayMaxGettingScorer},
			    #{homeMaxGettingScorerGameSituation},
			    #{awayMaxGettingScorerGameSituation},
			    #{homeTeamHomeScore},
			    #{homeTeamHomeLost},
			    #{awayTeamHomeScore},
			    #{awayTeamHomeLost},
			    #{homeTeamAwayScore},
			    #{homeTeamAwayLost},
			    #{awayTeamAwayScore},
			    #{awayTeamAwayLost},
			    #{noticeFlg},
			    #{gameLink},
			    #{goalTime},
			    #{goalTeamMember},
			    #{judge},
			    #{homeTeamStyle},
			    #{awayTeamStyle},
			    #{probablity},
			    #{predictionScoreTime},
			    #{gameId},
			    #{matchId},
			    #{timeSortSeconds},
			    'SYSTEM',
			    NOW(),
			    'SYSTEM',
			    NOW()
			)
			""")
	int insert(RealDataProcessEntity entity);

	@Update("""
			UPDATE real_data_process SET
			    condition_result_data_seq_id = #{conditionResultDataSeqId},
			    data_category = #{dataCategory},
			    times = #{times},
			    home_rank = #{homeRank},
			    away_rank = #{awayRank},
			    home_team_name = #{homeTeamName},
			    away_team_name = #{awayTeamName},
			    home_score = #{homeScore},
			    away_score = #{awayScore},
			    home_exp = #{homeExp},
			    away_exp = #{awayExp},
			    home_in_goal_exp = #{homeInGoalExp},
			    away_in_goal_exp = #{awayInGoalExp},
			    home_donation = #{homeDonation},
			    away_donation = #{awayDonation},
			    home_shoot_all = #{homeShootAll},
			    away_shoot_all = #{awayShootAll},
			    home_shoot_in = #{homeShootIn},
			    away_shoot_in = #{awayShootIn},
			    home_shoot_out = #{homeShootOut},
			    away_shoot_out = #{awayShootOut},
			    home_block_shoot = #{homeBlockShoot},
			    away_block_shoot = #{awayBlockShoot},
			    home_big_chance = #{homeBigChance},
			    away_big_chance = #{awayBigChance},
			    home_corner = #{homeCorner},
			    away_corner = #{awayCorner},
			    home_box_shoot_in = #{homeBoxShootIn},
			    away_box_shoot_in = #{awayBoxShootIn},
			    home_box_shoot_out = #{homeBoxShootOut},
			    away_box_shoot_out = #{awayBoxShootOut},
			    home_goal_post = #{homeGoalPost},
			    away_goal_post = #{awayGoalPost},
			    home_goal_head = #{homeGoalHead},
			    away_goal_head = #{awayGoalHead},
			    home_keeper_save = #{homeKeeperSave},
			    away_keeper_save = #{awayKeeperSave},
			    home_free_kick = #{homeFreeKick},
			    away_free_kick = #{awayFreeKick},
			    home_offside = #{homeOffside},
			    away_offside = #{awayOffside},
			    home_foul = #{homeFoul},
			    away_foul = #{awayFoul},
			    home_yellow_card = #{homeYellowCard},
			    away_yellow_card = #{awayYellowCard},
			    home_red_card = #{homeRedCard},
			    away_red_card = #{awayRedCard},
			    home_slow_in = #{homeSlowIn},
			    away_slow_in = #{awaySlowIn},
			    home_box_touch = #{homeBoxTouch},
			    away_box_touch = #{awayBoxTouch},
			    home_pass_count = #{homePassCount},
			    away_pass_count = #{awayPassCount},
			    home_long_pass_count = #{homeLongPassCount},
			    away_long_pass_count = #{awayLongPassCount},
			    home_final_third_pass_count = #{homeFinalThirdPassCount},
			    away_final_third_pass_count = #{awayFinalThirdPassCount},
			    home_cross_count = #{homeCrossCount},
			    away_cross_count = #{awayCrossCount},
			    home_tackle_count = #{homeTackleCount},
			    away_tackle_count = #{awayTackleCount},
			    home_clear_count = #{homeClearCount},
			    away_clear_count = #{awayClearCount},
			    home_duel_count = #{homeDuelCount},
			    away_duel_count = #{awayDuelCount},
			    home_intercept_count = #{homeInterceptCount},
			    away_intercept_count = #{awayInterceptCount},
			    record_time = CAST(#{recordTime} AS timestamptz),
			    weather = #{weather},
			    temparature = #{temparature},
			    humid = #{humid},
			    judge_member = #{judgeMember},
			    home_manager = #{homeManager},
			    away_manager = #{awayManager},
			    home_formation = #{homeFormation},
			    away_formation = #{awayFormation},
			    studium = #{studium},
			    capacity = #{capacity},
			    audience = #{audience},
			    location = #{location},
			    home_max_getting_scorer = #{homeMaxGettingScorer},
			    away_max_getting_scorer = #{awayMaxGettingScorer},
			    home_max_getting_scorer_game_situation = #{homeMaxGettingScorerGameSituation},
			    away_max_getting_scorer_game_situation = #{awayMaxGettingScorerGameSituation},
			    home_team_home_score = #{homeTeamHomeScore},
			    home_team_home_lost = #{homeTeamHomeLost},
			    away_team_home_score = #{awayTeamHomeScore},
			    away_team_home_lost = #{awayTeamHomeLost},
			    home_team_away_score = #{homeTeamAwayScore},
			    home_team_away_lost = #{homeTeamAwayLost},
			    away_team_away_score = #{awayTeamAwayScore},
			    away_team_away_lost = #{awayTeamAwayLost},
			    notice_flg = #{noticeFlg},
			    game_link = #{gameLink},
			    goal_time = #{goalTime},
			    goal_team_member = #{goalTeamMember},
			    judge = #{judge},
			    home_team_style = #{homeTeamStyle},
			    away_team_style = #{awayTeamStyle},
			    probablity = #{probablity},
			    prediction_score_time = #{predictionScoreTime},
			    game_id = #{gameId},
			    match_id = #{matchId},
			    time_sort_seconds = #{timeSortSeconds},
			    update_id = 'SYSTEM',
			    update_time = NOW()
			WHERE match_id = #{matchId}
			""")
	int updateByMatchId(RealDataProcessEntity entity);

	@Insert("""
			INSERT INTO real_data_process (
			    condition_result_data_seq_id,
			    data_category,
			    times,
			    home_rank,
			    away_rank,
			    home_team_name,
			    away_team_name,
			    home_score,
			    away_score,
			    home_exp,
			    away_exp,
			    home_in_goal_exp,
			    away_in_goal_exp,
			    home_donation,
			    away_donation,
			    home_shoot_all,
			    away_shoot_all,
			    home_shoot_in,
			    away_shoot_in,
			    home_shoot_out,
			    away_shoot_out,
			    home_block_shoot,
			    away_block_shoot,
			    home_big_chance,
			    away_big_chance,
			    home_corner,
			    away_corner,
			    home_box_shoot_in,
			    away_box_shoot_in,
			    home_box_shoot_out,
			    away_box_shoot_out,
			    home_goal_post,
			    away_goal_post,
			    home_goal_head,
			    away_goal_head,
			    home_keeper_save,
			    away_keeper_save,
			    home_free_kick,
			    away_free_kick,
			    home_offside,
			    away_offside,
			    home_foul,
			    away_foul,
			    home_yellow_card,
			    away_yellow_card,
			    home_red_card,
			    away_red_card,
			    home_slow_in,
			    away_slow_in,
			    home_box_touch,
			    away_box_touch,
			    home_pass_count,
			    away_pass_count,
			    home_long_pass_count,
			    away_long_pass_count,
			    home_final_third_pass_count,
			    away_final_third_pass_count,
			    home_cross_count,
			    away_cross_count,
			    home_tackle_count,
			    away_tackle_count,
			    home_clear_count,
			    away_clear_count,
			    home_duel_count,
			    away_duel_count,
			    home_intercept_count,
			    away_intercept_count,
			    record_time,
			    weather,
			    temparature,
			    humid,
			    judge_member,
			    home_manager,
			    away_manager,
			    home_formation,
			    away_formation,
			    studium,
			    capacity,
			    audience,
			    location,
			    home_max_getting_scorer,
			    away_max_getting_scorer,
			    home_max_getting_scorer_game_situation,
			    away_max_getting_scorer_game_situation,
			    home_team_home_score,
			    home_team_home_lost,
			    away_team_home_score,
			    away_team_home_lost,
			    home_team_away_score,
			    home_team_away_lost,
			    away_team_away_score,
			    away_team_away_lost,
			    notice_flg,
			    game_link,
			    goal_time,
			    goal_team_member,
			    judge,
			    home_team_style,
			    away_team_style,
			    probablity,
			    prediction_score_time,
			    game_id,
			    match_id,
			    time_sort_seconds,
			    register_id,
			    register_time,
			    update_id,
			    update_time
			) VALUES (
			    #{conditionResultDataSeqId},
			    #{dataCategory},
			    #{times},
			    #{homeRank},
			    #{awayRank},
			    #{homeTeamName},
			    #{awayTeamName},
			    #{homeScore},
			    #{awayScore},
			    #{homeExp},
			    #{awayExp},
			    #{homeInGoalExp},
			    #{awayInGoalExp},
			    #{homeDonation},
			    #{awayDonation},
			    #{homeShootAll},
			    #{awayShootAll},
			    #{homeShootIn},
			    #{awayShootIn},
			    #{homeShootOut},
			    #{awayShootOut},
			    #{homeBlockShoot},
			    #{awayBlockShoot},
			    #{homeBigChance},
			    #{awayBigChance},
			    #{homeCorner},
			    #{awayCorner},
			    #{homeBoxShootIn},
			    #{awayBoxShootIn},
			    #{homeBoxShootOut},
			    #{awayBoxShootOut},
			    #{homeGoalPost},
			    #{awayGoalPost},
			    #{homeGoalHead},
			    #{awayGoalHead},
			    #{homeKeeperSave},
			    #{awayKeeperSave},
			    #{homeFreeKick},
			    #{awayFreeKick},
			    #{homeOffside},
			    #{awayOffside},
			    #{homeFoul},
			    #{awayFoul},
			    #{homeYellowCard},
			    #{awayYellowCard},
			    #{homeRedCard},
			    #{awayRedCard},
			    #{homeSlowIn},
			    #{awaySlowIn},
			    #{homeBoxTouch},
			    #{awayBoxTouch},
			    #{homePassCount},
			    #{awayPassCount},
			    #{homeLongPassCount},
			    #{awayLongPassCount},
			    #{homeFinalThirdPassCount},
			    #{awayFinalThirdPassCount},
			    #{homeCrossCount},
			    #{awayCrossCount},
			    #{homeTackleCount},
			    #{awayTackleCount},
			    #{homeClearCount},
			    #{awayClearCount},
			    #{homeDuelCount},
			    #{awayDuelCount},
			    #{homeInterceptCount},
			    #{awayInterceptCount},
			    CAST(#{recordTime} AS timestamptz),
			    #{weather},
			    #{temparature},
			    #{humid},
			    #{judgeMember},
			    #{homeManager},
			    #{awayManager},
			    #{homeFormation},
			    #{awayFormation},
			    #{studium},
			    #{capacity},
			    #{audience},
			    #{location},
			    #{homeMaxGettingScorer},
			    #{awayMaxGettingScorer},
			    #{homeMaxGettingScorerGameSituation},
			    #{awayMaxGettingScorerGameSituation},
			    #{homeTeamHomeScore},
			    #{homeTeamHomeLost},
			    #{awayTeamHomeScore},
			    #{awayTeamHomeLost},
			    #{homeTeamAwayScore},
			    #{homeTeamAwayLost},
			    #{awayTeamAwayScore},
			    #{awayTeamAwayLost},
			    #{noticeFlg},
			    #{gameLink},
			    #{goalTime},
			    #{goalTeamMember},
			    #{judge},
			    #{homeTeamStyle},
			    #{awayTeamStyle},
			    #{probablity},
			    #{predictionScoreTime},
			    #{gameId},
			    #{matchId},
			    #{timeSortSeconds},
			    'SYSTEM',
			    NOW(),
			    'SYSTEM',
			    NOW()
			)
			ON CONFLICT (match_id) DO UPDATE SET
			    condition_result_data_seq_id = EXCLUDED.condition_result_data_seq_id,
			    data_category = EXCLUDED.data_category,
			    times = EXCLUDED.times,
			    home_rank = EXCLUDED.home_rank,
			    away_rank = EXCLUDED.away_rank,
			    home_team_name = EXCLUDED.home_team_name,
			    away_team_name = EXCLUDED.away_team_name,
			    home_score = EXCLUDED.home_score,
			    away_score = EXCLUDED.away_score,
			    home_exp = EXCLUDED.home_exp,
			    away_exp = EXCLUDED.away_exp,
			    home_in_goal_exp = EXCLUDED.home_in_goal_exp,
			    away_in_goal_exp = EXCLUDED.away_in_goal_exp,
			    home_donation = EXCLUDED.home_donation,
			    away_donation = EXCLUDED.away_donation,
			    home_shoot_all = EXCLUDED.home_shoot_all,
			    away_shoot_all = EXCLUDED.away_shoot_all,
			    home_shoot_in = EXCLUDED.home_shoot_in,
			    away_shoot_in = EXCLUDED.away_shoot_in,
			    home_shoot_out = EXCLUDED.home_shoot_out,
			    away_shoot_out = EXCLUDED.away_shoot_out,
			    home_block_shoot = EXCLUDED.home_block_shoot,
			    away_block_shoot = EXCLUDED.away_block_shoot,
			    home_big_chance = EXCLUDED.home_big_chance,
			    away_big_chance = EXCLUDED.away_big_chance,
			    home_corner = EXCLUDED.home_corner,
			    away_corner = EXCLUDED.away_corner,
			    home_box_shoot_in = EXCLUDED.home_box_shoot_in,
			    away_box_shoot_in = EXCLUDED.away_box_shoot_in,
			    home_box_shoot_out = EXCLUDED.home_box_shoot_out,
			    away_box_shoot_out = EXCLUDED.away_box_shoot_out,
			    home_goal_post = EXCLUDED.home_goal_post,
			    away_goal_post = EXCLUDED.away_goal_post,
			    home_goal_head = EXCLUDED.home_goal_head,
			    away_goal_head = EXCLUDED.away_goal_head,
			    home_keeper_save = EXCLUDED.home_keeper_save,
			    away_keeper_save = EXCLUDED.away_keeper_save,
			    home_free_kick = EXCLUDED.home_free_kick,
			    away_free_kick = EXCLUDED.away_free_kick,
			    home_offside = EXCLUDED.home_offside,
			    away_offside = EXCLUDED.away_offside,
			    home_foul = EXCLUDED.home_foul,
			    away_foul = EXCLUDED.away_foul,
			    home_yellow_card = EXCLUDED.home_yellow_card,
			    away_yellow_card = EXCLUDED.away_yellow_card,
			    home_red_card = EXCLUDED.home_red_card,
			    away_red_card = EXCLUDED.away_red_card,
			    home_slow_in = EXCLUDED.home_slow_in,
			    away_slow_in = EXCLUDED.away_slow_in,
			    home_box_touch = EXCLUDED.home_box_touch,
			    away_box_touch = EXCLUDED.away_box_touch,
			    home_pass_count = EXCLUDED.home_pass_count,
			    away_pass_count = EXCLUDED.away_pass_count,
			    home_long_pass_count = EXCLUDED.home_long_pass_count,
			    away_long_pass_count = EXCLUDED.away_long_pass_count,
			    home_final_third_pass_count = EXCLUDED.home_final_third_pass_count,
			    away_final_third_pass_count = EXCLUDED.away_final_third_pass_count,
			    home_cross_count = EXCLUDED.home_cross_count,
			    away_cross_count = EXCLUDED.away_cross_count,
			    home_tackle_count = EXCLUDED.home_tackle_count,
			    away_tackle_count = EXCLUDED.away_tackle_count,
			    home_clear_count = EXCLUDED.home_clear_count,
			    away_clear_count = EXCLUDED.away_clear_count,
			    home_duel_count = EXCLUDED.home_duel_count,
			    away_duel_count = EXCLUDED.away_duel_count,
			    home_intercept_count = EXCLUDED.home_intercept_count,
			    away_intercept_count = EXCLUDED.away_intercept_count,
			    record_time = EXCLUDED.record_time,
			    weather = EXCLUDED.weather,
			    temparature = EXCLUDED.temparature,
			    humid = EXCLUDED.humid,
			    judge_member = EXCLUDED.judge_member,
			    home_manager = EXCLUDED.home_manager,
			    away_manager = EXCLUDED.away_manager,
			    home_formation = EXCLUDED.home_formation,
			    away_formation = EXCLUDED.away_formation,
			    studium = EXCLUDED.studium,
			    capacity = EXCLUDED.capacity,
			    audience = EXCLUDED.audience,
			    location = EXCLUDED.location,
			    home_max_getting_scorer = EXCLUDED.home_max_getting_scorer,
			    away_max_getting_scorer = EXCLUDED.away_max_getting_scorer,
			    home_max_getting_scorer_game_situation = EXCLUDED.home_max_getting_scorer_game_situation,
			    away_max_getting_scorer_game_situation = EXCLUDED.away_max_getting_scorer_game_situation,
			    home_team_home_score = EXCLUDED.home_team_home_score,
			    home_team_home_lost = EXCLUDED.home_team_home_lost,
			    away_team_home_score = EXCLUDED.away_team_home_score,
			    away_team_home_lost = EXCLUDED.away_team_home_lost,
			    home_team_away_score = EXCLUDED.home_team_away_score,
			    home_team_away_lost = EXCLUDED.home_team_away_lost,
			    away_team_away_score = EXCLUDED.away_team_away_score,
			    away_team_away_lost = EXCLUDED.away_team_away_lost,
			    notice_flg = EXCLUDED.notice_flg,
			    game_link = EXCLUDED.game_link,
			    goal_time = EXCLUDED.goal_time,
			    goal_team_member = EXCLUDED.goal_team_member,
			    judge = EXCLUDED.judge,
			    home_team_style = EXCLUDED.home_team_style,
			    away_team_style = EXCLUDED.away_team_style,
			    probablity = EXCLUDED.probablity,
			    prediction_score_time = EXCLUDED.prediction_score_time,
			    game_id = EXCLUDED.game_id,
			    time_sort_seconds = EXCLUDED.time_sort_seconds,
			    update_id = 'SYSTEM',
			    update_time = NOW()
			""")
	int upsertByMatchId(RealDataProcessEntity entity);

}
